# Generated by Django 4.1.5 on 2024-02-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.groupsubject'),
        ),
    ]
