# Generated by Django 4.1.5 on 2024-02-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_level_principal_teacher_alter_level_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.series'),
        ),
        migrations.AlterField(
            model_name='sanctionappreciation',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.academicyear'),
        ),
        migrations.AlterField(
            model_name='sanctionappreciation',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.classroom'),
        ),
        migrations.AlterField(
            model_name='sanctionappreciation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.student'),
        ),
    ]
