# Generated by Django 4.1.5 on 2024-02-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_level_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.series'),
        ),
    ]
