# Generated by Django 4.1.5 on 2024-02-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_level_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='person_in_charge',
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
