# Generated by Django 4.1.5 on 2024-02-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_program_person_in_charge_program_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
