# Generated by Django 4.1.5 on 2024-02-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_level_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='serie',
        ),
        migrations.AddField(
            model_name='assessment',
            name='period',
            field=models.CharField(choices=[('Premier trimestre', 'Premier trimestre'), ('Deuxième trimestre', 'Deuxième trimestre'), ('Troisième trimestre', 'Troisième trimestre'), ('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.academicyear'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.classroom'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subject'),
        ),
    ]
