# Generated by Django 4.1.5 on 2024-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_assessment_type_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname_one', models.CharField(max_length=50)),
                ('firstname_one', models.CharField(max_length=50)),
                ('address_one', models.CharField(max_length=50)),
                ('email_one', models.CharField(max_length=120)),
                ('tel_one', models.CharField(max_length=20)),
                ('picture_one', models.ImageField(upload_to='parents_images')),
                ('lastname_seconde', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname_seconde', models.CharField(blank=True, max_length=50, null=True)),
                ('address_seconde', models.CharField(blank=True, max_length=50, null=True)),
                ('email_seconde', models.CharField(blank=True, max_length=120, null=True)),
                ('tel_seconde', models.CharField(blank=True, max_length=20, null=True)),
                ('picture_seconde', models.ImageField(blank=True, null=True, upload_to='parents_images')),
            ],
        ),
    ]
