# Generated by Django 4.1.5 on 2024-03-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='career',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='semester',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.classroom'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='type',
            field=models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'College'), ('Lycée', 'Lycée')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.parent'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.student'),
        ),
    ]
