# Generated by Django 4.1.5 on 2024-03-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_reportcard_career_remove_reportcard_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email_one',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
