# Generated by Django 4.1.5 on 2024-03-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_parent_email_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
