# Generated by Django 4.1.5 on 2024-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_parent_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
