# Generated by Django 4.1.5 on 2024-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_parent_created_at_parent_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='picture_one',
            field=models.ImageField(blank=True, null=True, upload_to='parents_images'),
        ),
    ]
