# Generated by Django 4.1.5 on 2024-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='note_exam',
            field=models.IntegerField(default=0),
        ),
    ]
