# Generated by Django 4.1.5 on 2024-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_assessment_type_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
