# Generated by Django 4.1.5 on 2024-03-30 07:13

import backend.models.gestion_ecole
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_etablishment_code_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablishment',
            name='code',
            field=backend.models.gestion_ecole.UUID4Field(editable=False, max_length=12, null=True, unique=True),
        ),
    ]
